version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 4

.qk
    h q[0]
    h q[1]
    h q[2]
    h q[3]
    cnot q[0],q[1]
    rz q[1], 5.50503
    cnot q[0],q[1]
    x q[0]
    rz q[0], 2.75252
    x q[0]
    rz q[0], 2.75252
    cnot q[0],q[3]
    rz q[3], 5.50503
    cnot q[0],q[3]
    x q[0]
    rz q[0], 2.75252
    x q[0]
    rz q[0], 2.75252
    cnot q[1],q[2]
    rz q[2], 5.50503
    cnot q[1],q[2]
    x q[0]
    rz q[0], 2.75252
    x q[0]
    rz q[0], 2.75252
    cnot q[3],q[2]
    rz q[2], 5.50503
    cnot q[3],q[2]
    x q[0]
    rz q[0], 2.75252
    x q[0]
    rz q[0], 2.75252
    h q[0]
    rz q[0], -8.70704
    h q[0]
    h q[1]
    rz q[1], -8.70704
    h q[1]
    h q[3]
    rz q[3], -8.70704
    h q[3]
    h q[2]
    rz q[2], -8.70704
    h q[2]
    cnot q[0],q[1]
    rz q[1], 2.06639
    cnot q[0],q[1]
    x q[0]
    rz q[0], 1.03319
    x q[0]
    rz q[0], 1.03319
    cnot q[0],q[3]
    rz q[3], 2.06639
    cnot q[0],q[3]
    x q[0]
    rz q[0], 1.03319
    x q[0]
    rz q[0], 1.03319
    cnot q[1],q[2]
    rz q[2], 2.06639
    cnot q[1],q[2]
    x q[0]
    rz q[0], 1.03319
    x q[0]
    rz q[0], 1.03319
    cnot q[3],q[2]
    rz q[2], 2.06639
    cnot q[3],q[2]
    x q[0]
    rz q[0], 1.03319
    x q[0]
    rz q[0], 1.03319
    h q[0]
    rz q[0], -10.6622
    h q[0]
    h q[1]
    rz q[1], -10.6622
    h q[1]
    h q[3]
    rz q[3], -10.6622
    h q[3]
    h q[2]
    rz q[2], -10.6622
    h q[2]
    cnot q[0],q[1]
    rz q[1], 1.76688
    cnot q[0],q[1]
    x q[0]
    rz q[0], 0.883442
    x q[0]
    rz q[0], 0.883442
    cnot q[0],q[3]
    rz q[3], 1.76688
    cnot q[0],q[3]
    x q[0]
    rz q[0], 0.883442
    x q[0]
    rz q[0], 0.883442
    cnot q[1],q[2]
    rz q[2], 1.76688
    cnot q[1],q[2]
    x q[0]
    rz q[0], 0.883442
    x q[0]
    rz q[0], 0.883442
    cnot q[3],q[2]
    rz q[2], 1.76688
    cnot q[3],q[2]
    x q[0]
    rz q[0], 0.883442
    x q[0]
    rz q[0], 0.883442
    h q[0]
    rz q[0], -4.53233
    h q[0]
    h q[1]
    rz q[1], -4.53233
    h q[1]
    h q[3]
    rz q[3], -4.53233
    h q[3]
    h q[2]
    rz q[2], -4.53233
    h q[2]
